// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_user_from_refresh.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromRefresh = `-- name: GetUserFromRefresh :one
SELECT refresh_tokens.user_id FROM refresh_tokens
JOIN users
ON refresh_tokens.user_id = users.id
WHERE refresh_tokens.token = $1
    AND refresh_tokens.expires_at > NOW()
    AND refresh_tokens.revoked_at IS NULL
`

func (q *Queries) GetUserFromRefresh(ctx context.Context, token string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefresh, token)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
